#!/usr/bin/bash
tablica=(1 5 9 12 8 4 7 6 20)
a=${#tablica[@]}
for ((i=0; i<a-1; i++));do
for ((j=0; j<a-1-i;j++));do
if [ ${tablica[j]} -gt ${tablica[j+1]} ];then
temp=${tablica[j]}
tablica[j]=${tablica[j+1]}
tablica[j+1]=$temp
fi
done
echo ${tablica[@]}
done



